title: 
logo: /imgages/logo.png
description: Build a Minecraft Server using a Raspberry Pi 4! Supports common Servers, SCP and Wifi Connect
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
